name: Anonymous Passwordless SSH Server with Bore.pub

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install SSH Server and Rust
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server curl build-essential
        
        # Install Rust and Cargo
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        
    - name: Install Bore CLI using Cargo
      run: |
        source $HOME/.cargo/env
        cargo install bore-cli
        
    - name: Configure Passwordless SSH Server
      run: |
        # Configure SSH for NO authentication
        sudo tee /etc/ssh/sshd_config > /dev/null <<EOF
        Port 22
        Protocol 2
        
        # Disable all authentication methods
        PasswordAuthentication no
        PubkeyAuthentication no
        ChallengeResponseAuthentication no
        UsePAM no
        
        # Allow empty passwords and permit root login
        PermitRootLogin yes
        PermitEmptyPasswords yes
        
        # Disable strict modes for anonymous access
        StrictModes no
        
        # Allow anyone to connect
        AllowUsers *
        
        # Other settings
        X11Forwarding yes
        PrintMotd yes
        Subsystem sftp /usr/lib/openssh/sftp-server
        EOF
        
    - name: Create Users with Empty Passwords
      run: |
        # Set empty password for root
        sudo passwd -d root
        
        # Create topuser with empty password
        sudo useradd -m -s /bin/bash topuser
        sudo passwd -d topuser
        
        # Add topuser to sudo group
        sudo usermod -aG sudo topuser
        echo 'topuser ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/topuser
        sudo chmod 440 /etc/sudoers.d/topuser
        
    - name: Start and Enable SSH Service
      run: |
        # Generate SSH host keys
        sudo ssh-keygen -A
        
        # Enable SSH service to start on boot
        sudo systemctl enable ssh
        
        # Start SSH service
        sudo systemctl start ssh
        
        # Verify SSH is running
        echo "🔍 SSH Service Status:"
        sudo systemctl status ssh --no-pager
        
        # Check if SSH is listening on port 22
        echo ""
        echo "🔍 SSH Port Check:"
        sudo netstat -tlnp | grep :22 || echo "SSH not listening on port 22"
        
        # Test local SSH connection
        echo ""
        echo "🔍 Testing Local SSH:"
        timeout 5 ssh -o StrictHostKeyChecking=no -o BatchMode=yes root@localhost echo "SSH is working!" || echo "Local SSH test failed"
        
    - name: Start Bore Tunnel and Display Connection Info
      run: |
        source $HOME/.cargo/env
        echo "🚀 Starting bore tunnel for SSH..."
        
        # Start bore tunnel in background
        $HOME/.cargo/bin/bore local 22 --to bore.pub > bore_output.txt 2>&1 &
        BORE_PID=$!
        
        # Wait for connection to establish
        sleep 15
        
        # Display connection information
        echo "========================================"
        echo "🎯 SSH SERVER IS READY!"
        echo "========================================"
        
        if [ -f bore_output.txt ]; then
          echo "📄 Bore Output:"
          cat bore_output.txt
          echo ""
          
          # Extract port number
          TUNNEL_PORT=$(cat bore_output.txt | grep -oE 'bore\.pub:[0-9]+' | cut -d: -f2)
          if [ ! -z "$TUNNEL_PORT" ]; then
            echo "🌐 SSH Connection Commands:"
            echo "   ssh root@bore.pub -p $TUNNEL_PORT"
            echo "   ssh topuser@bore.pub -p $TUNNEL_PORT"
            echo ""
            echo "💡 No password required - just press Enter when prompted!"
          else
            echo "⚠️  Could not extract port number from bore output"
          fi
        else
          echo "⚠️  Bore output file not found"
        fi
        
        echo "========================================"
        echo "📋 Final Status Check:"
        echo "   • SSH Service: $(sudo systemctl is-active ssh)"
        echo "   • SSH Port 22: $(sudo netstat -tln | grep :22 | wc -l) listener(s)"
        echo "   • Bore Process: $BORE_PID"
        echo "========================================"
        
        # Keep the workflow running for 6 hours
        echo "🔄 Keeping server alive for 6 hours..."
        sleep 21600
        
